
// const score = 100;

// console.log(typeof score)



// for(let i = 100; i<= -0.111111; i++){

//     console.log(i.toFixed)

// }

// const balance = new Number(40000);


// console.log(balance.toString().length)



// const fus = 100000000000000000000000000000000000;

// console.log(fus.toLocaleString())







///++++++++++++++MATHS+++++++++++++++++++++++




console.log(Math)
console.log(Math.abs(34))
console.log(Math.round(3437.87238263))
console.log(Math.ceil(3437.87238263))
console.log(Math.floor(3437.87238263))
